
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:14.18.1

stages:
  - install
  - build

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  tags:
    - docker
  script:
    - npm -v
    - node -v
    - npm install
  artifacts:
        paths:
          - node_modules/

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
