import { Table } from '..';

/* eslint-disable no-unused-vars */
export enum NotificationType {
  SAMPLE_NOTIFIER = 'SAMPLE_NOTIFIER',
  ACADEMIC_PROGRAM_INCHARGE_NOTIFIER = 'ACADEMIC_PROGRAM_INCHARGE_NOTIFIER',
  ACADEMIC_PROGRAM_ENROLLMENT_NOTIFIER = 'ACADEMIC_PROGRAM_ENROLLMENT_NOTIFIER',
  NEW_MODULE_ASSIGNED_NOTIFIER = 'NEW_MODULE_ASSIGNED_NOTIFIER',
  NEW_SUBJECT_ASSIGNED_NOTIFIER = 'NEW_SUBJECT_ASSIGNED_NOTIFIER',
  NEW_ROLE_ASSIGNED_NOTIFIER = 'NEW_ROLE_ASSIGNED_NOTIFIER',
  NEW_LEVEL_ASSIGNED_NOTIFIER = 'NEW_LEVEL_ASSIGNED_NOTIFIER',
  NEW_LEVEL_PROMOTION_NOTIFIER = 'NEW_LEVEL_PROMOTION_NOTIFIER',
  APRROVAL_OF_EVALUATION_NOTIFIER = 'APRROVAL_OF_EVALUATION_NOTIFIER',
  EVALUATION_REVIEWER_ASSIGNMENT_NOTIFIER = 'EVALUATION_REVIEWER_ASSIGNMENT_NOTIFIER',
  EVALUATION_MARKER_ASSIGNMENT_NOTIFIER = 'EVALUATION_MARKER_ASSIGNMENT_NOTIFIER',
  EVALUATION_APPROVER_ASSIGNMENT_NOTIFIER = 'EVALUATION_APPROVER_ASSIGNMENT_NOTIFIER',
  NEW_EVALUATION_NOTIFIER = 'NEW_EVALUATION_NOTIFIER',
  NEW_ADMISSION_TO_ACADEMY_NOTIFIER = 'NEW_ADMISSION_TO_ACADEMY_NOTIFIER',
  NEW_ADMISSION_TO_INSTITUTION_NOTIFIER = 'NEW_ADMISSION_TO_INSTITUTION_NOTIFIER',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
}

export interface NotificationInfo extends Table {
  title: string;
  message: string;
  notification_type: NotificationType;
  notification_user_beneficiary: string;
  notification_entity_beneficiary_uuid: string;
  notification_entity_beneficiary_long: string;
  notifaction_status: NotificationType;
}
